services:
  # База данных PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: wabapp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: wabapp
      POSTGRES_USER: wabapp_user
      POSTGRES_PASSWORD: wabapp_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - wabapp_network

  # Redis для кэширования
  redis:
    image: redis:7-alpine
    container_name: wabapp_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - wabapp_network

  # Backend API
  backend:
    build: ./backend
    container_name: wabapp_backend
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: 3001

      # База данных
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: wabapp
      DB_USER: wabapp_user
      DB_PASSWORD: wabapp_password

      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379

      # AMO CRM
      AMO_SUBDOMAIN: ${AMO_SUBDOMAIN:-your_subdomain}
      AMO_CLIENT_ID: ${AMO_CLIENT_ID:-your_client_id}
      AMO_CLIENT_SECRET: ${AMO_CLIENT_SECRET:-your_client_secret}

      # Gupshup
      GUPSHUP_API_KEY: ${GUPSHUP_API_KEY:-your_api_key}
      GUPSHUP_APP_NAME: ${GUPSHUP_APP_NAME:-your_app_name}

      # JWT
      JWT_SECRET: ${JWT_SECRET:-your_jwt_secret_key}

      # URL настройки для localhost и реального IP
      BASE_URL: ${BASE_URL:-http://localhost:3001}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3000}
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost:3000,http://127.0.0.1:3000,http://83.166.238.230:3000}

    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    ports:
      - "${BACKEND_PORT:-3001}:3001"
    networks:
      - wabapp_network

  # Frontend React
  frontend:
    build: 
      context: ./frontend
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:3001}
        REACT_APP_WS_URL: ${REACT_APP_WS_URL:-ws://localhost:3001}
    container_name: wabapp_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    networks:
      - wabapp_network

volumes:
  postgres_data:

networks:
  wabapp_network:
    driver: bridge
