
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-amo-mvp
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      # Укажите здесь переменные из вашего .env
      - PORT=3001
      - GUPSHUP_API_KEY=${GUPSHUP_API_KEY}
      - GUPSHUP_APP_NAME=${GUPSHUP_APP_NAME}
      - AMO_CLIENT_ID=${AMO_CLIENT_ID}
      - AMO_CLIENT_SECRET=${AMO_CLIENT_SECRET}
      - AMO_REDIRECT_URI=${AMO_REDIRECT_URI}
      - BASE_URL=${BASE_URL}
    volumes:
      # Монтируем папку с .env, если нужно
      - ./.env:/app/.env:ro

networks:
  default:
    name: whatsapp-amo-net
