services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wabapp_app
    restart: unless-stopped
    env_file:
      - ./.env
    expose:
      - "3001"
    networks:
      - wabapp

  nginx:
    image: nginx:alpine
    container_name: wabapp_nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - wabapp

networks:
  wabapp:
    driver: bridge
